# Site settings
title: 漳浦县上尚品贸易有限公司
email: sspios@163.com
url: http://www.shangshangpin.tk
description: "ZhangPu County Shangshangpin Trading Co., Ltd."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: ZhangPu County Shangshangpin Trading Co., Ltd.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Build settings
markdown: kramdown
permalink: pretty
